### ISSUE TITLE
Crypto obfuscate 

### ISSUE THREAD

**Issue by pavelkarpov8675** [Raffy27/OrionBot#1]
Any ways to crypto obfuscate this pascal bot?

**Comment by Raffy27** [comment]
Delphi is a native language, so obfuscation is not very straightforward. Strings are stored as plaintext throughout the code - you can centralize them (maybe use **resourcestrings**), apply any symmetric cryptographic algorithms you'd like, and decrypt them during runtime. If you're looking to encrypt the binary itself, you could simply **xor** the bytes and decrypt them during runtime.

I'm not sure I understood your question correctly.
