### ISSUE TITLE
OrionBot never connects to server

### ISSUE THREAD

**Issue by SinfullySoul** [Raffy27/OrionBot#2]
it's tor or the bot itself never connect, All my firewalls was turn off for both windows 7 and 10.
the OrionServer was run on a Linux server and the Panel was running a window 10 pc. the server and panel did connect over tor and I could upload files to the server and download files from the server.

**Comment by Raffy27** [comment]
Please describe the issue in detail. What error messages (if any) did you encounter? Was Tor running on both your Linux system and your PC? What configuration was Tor launched with and what did its log say? What are your Panel settings?
Please ensure that the appropriate local ports are open. See the **Setup Guide**.
